//! Fixtures were generated by decoding and re-encoding the original Effect
//! contracts at packages/contracts/src/{baseSchemas,providerInstance,modelSelection}.ts.
use serde::{Deserialize, Serialize};
use serde_json::Value;
use t3_contracts::*;

#[derive(Deserialize)]
struct Fixture {
    schema: String,
    input: Value,
    valid: bool,
    decoded_valid: Option<bool>,
    output: Option<Value>,
}
fn roundtrip<T: serde::de::DeserializeOwned + Serialize>(
    value: Value,
) -> Result<Value, serde_json::Error> {
    serde_json::from_value::<T>(value).and_then(serde_json::to_value)
}

#[test]
fn rust_codecs_match_original_effect_decode_and_encode_fixtures() {
    let fixtures: Vec<Fixture> =
        serde_json::from_str(include_str!("fixtures/original-codecs.json")).unwrap();
    for fixture in fixtures {
        let result = match fixture.schema.as_str() {
            "ThreadId" => roundtrip::<ThreadId>(fixture.input.clone()),
            "ProviderDriverKind" => roundtrip::<ProviderDriverKind>(fixture.input.clone()),
            "ProviderInstanceId" => roundtrip::<ProviderInstanceId>(fixture.input.clone()),
            "ModelSelection" => roundtrip::<ModelSelection>(fixture.input.clone()),
            schema => panic!("unsupported fixture codec {schema}"),
        };
        assert_eq!(
            result.is_ok(),
            fixture.valid,
            "{} input: {}",
            fixture.schema,
            fixture.input
        );
        if fixture.valid {
            assert_eq!(
                result.unwrap(),
                fixture.output.unwrap(),
                "{} input: {}",
                fixture.schema,
                fixture.input
            );
        }
    }
}

/// Generated by the original Schema.toCodecJson codecs, including each field's
/// missing/null/wrong-type behavior. These are reference outputs, not Rust snapshots.
#[test]
fn expanded_rust_codecs_match_original_json_wire_codecs() {
    fn checked_roundtrip<T: serde::de::DeserializeOwned + Serialize>(
        value: Value,
    ) -> (bool, Result<Value, serde_json::Error>) {
        match serde_json::from_value::<T>(value) {
            Ok(decoded) => (true, serde_json::to_value(decoded)),
            Err(error) => (false, Err(error)),
        }
    }
    let fixtures: Vec<Fixture> = include_str!("fixtures/expanded-codecs.jsonl")
        .lines()
        .map(|line| serde_json::from_str(line).unwrap())
        .collect();
    let mut failures = Vec::new();
    for fixture in fixtures {
        let (decoded_valid, result) = match fixture.schema.as_str() {
            // BEGIN ORIGINAL CODEC DISPATCH
            "AuthAccessSnapshot" => checked_roundtrip::<AuthAccessSnapshot>(fixture.input.clone()),
            "AuthAccessStreamEvent" => {
                checked_roundtrip::<AuthAccessStreamEvent>(fixture.input.clone())
            }
            "AuthAccessTokenResult" => {
                checked_roundtrip::<AuthAccessTokenResult>(fixture.input.clone())
            }
            "AuthBrowserSessionRequest" => {
                checked_roundtrip::<AuthBrowserSessionRequest>(fixture.input.clone())
            }
            "AuthBrowserSessionResult" => {
                checked_roundtrip::<AuthBrowserSessionResult>(fixture.input.clone())
            }
            "AuthClientMetadata" => checked_roundtrip::<AuthClientMetadata>(fixture.input.clone()),
            "AuthClientMetadataDeviceType" => {
                checked_roundtrip::<AuthClientMetadataDeviceType>(fixture.input.clone())
            }
            "AuthClientPresentationMetadata" => {
                checked_roundtrip::<AuthClientPresentationMetadata>(fixture.input.clone())
            }
            "AuthClientSession" => checked_roundtrip::<AuthClientSession>(fixture.input.clone()),
            "AuthCreatePairingCredentialInput" => {
                checked_roundtrip::<AuthCreatePairingCredentialInput>(fixture.input.clone())
            }
            "AuthEnvironmentScope" => {
                checked_roundtrip::<AuthEnvironmentScope>(fixture.input.clone())
            }
            "AuthGrantScope" => checked_roundtrip::<AuthGrantScope>(fixture.input.clone()),
            "AuthMcpApprovalDecision" => {
                checked_roundtrip::<AuthMcpApprovalDecision>(fixture.input.clone())
            }
            "AuthMcpApprovalDecisionRequest" => {
                checked_roundtrip::<AuthMcpApprovalDecisionRequest>(fixture.input.clone())
            }
            "AuthMcpApprovalDetails" => {
                checked_roundtrip::<AuthMcpApprovalDetails>(fixture.input.clone())
            }
            "AuthMcpApprovalRedirect" => {
                checked_roundtrip::<AuthMcpApprovalRedirect>(fixture.input.clone())
            }
            "AuthMcpAuthorizationRequest" => {
                checked_roundtrip::<AuthMcpAuthorizationRequest>(fixture.input.clone())
            }
            "AuthMcpAuthorizationServerMetadata" => {
                checked_roundtrip::<AuthMcpAuthorizationServerMetadata>(fixture.input.clone())
            }
            "AuthMcpClientAccess" => {
                checked_roundtrip::<AuthMcpClientAccess>(fixture.input.clone())
            }
            "AuthMcpClientRegistration" => {
                checked_roundtrip::<AuthMcpClientRegistration>(fixture.input.clone())
            }
            "AuthMcpProtectedResourceMetadata" => {
                checked_roundtrip::<AuthMcpProtectedResourceMetadata>(fixture.input.clone())
            }
            "AuthMcpRegisteredClient" => {
                checked_roundtrip::<AuthMcpRegisteredClient>(fixture.input.clone())
            }
            "AuthMcpRegistrationError" => {
                checked_roundtrip::<AuthMcpRegistrationError>(fixture.input.clone())
            }
            "AuthMcpTokenError" => checked_roundtrip::<AuthMcpTokenError>(fixture.input.clone()),
            "AuthMcpTokenRequest" => {
                checked_roundtrip::<AuthMcpTokenRequest>(fixture.input.clone())
            }
            "AuthMcpTokenResult" => checked_roundtrip::<AuthMcpTokenResult>(fixture.input.clone()),
            "AuthPairingCredentialResult" => {
                checked_roundtrip::<AuthPairingCredentialResult>(fixture.input.clone())
            }
            "AuthPairingLink" => checked_roundtrip::<AuthPairingLink>(fixture.input.clone()),
            "AuthRevokeClientSessionInput" => {
                checked_roundtrip::<AuthRevokeClientSessionInput>(fixture.input.clone())
            }
            "AuthRevokePairingLinkInput" => {
                checked_roundtrip::<AuthRevokePairingLinkInput>(fixture.input.clone())
            }
            "AuthSessionState" => checked_roundtrip::<AuthSessionState>(fixture.input.clone()),
            "AuthTokenExchangeRequest" => {
                checked_roundtrip::<AuthTokenExchangeRequest>(fixture.input.clone())
            }
            "AuthWebSocketTicketResult" => {
                checked_roundtrip::<AuthWebSocketTicketResult>(fixture.input.clone())
            }
            "ServerAuthBootstrapMethod" => {
                checked_roundtrip::<ServerAuthBootstrapMethod>(fixture.input.clone())
            }
            "ServerAuthDescriptor" => {
                checked_roundtrip::<ServerAuthDescriptor>(fixture.input.clone())
            }
            "ServerAuthPolicy" => checked_roundtrip::<ServerAuthPolicy>(fixture.input.clone()),
            "ServerAuthSessionMethod" => {
                checked_roundtrip::<ServerAuthSessionMethod>(fixture.input.clone())
            }
            "ProviderInstanceConfig" => {
                checked_roundtrip::<ProviderInstanceConfig>(fixture.input.clone())
            }
            "ProviderInstanceEnvironmentVariable" => {
                checked_roundtrip::<ProviderInstanceEnvironmentVariable>(fixture.input.clone())
            }
            "ProviderInstanceMutation" => {
                checked_roundtrip::<ProviderInstanceMutation>(fixture.input.clone())
            }
            "ProviderInstanceRef" => {
                checked_roundtrip::<ProviderInstanceRef>(fixture.input.clone())
            }
            "CustomModelEntry" => checked_roundtrip::<CustomModelEntry>(fixture.input.clone()),
            "CustomModelSetting" => checked_roundtrip::<CustomModelSetting>(fixture.input.clone()),
            "ModelCapabilities" => checked_roundtrip::<ModelCapabilities>(fixture.input.clone()),
            "ProviderOptionChoice" => {
                checked_roundtrip::<ProviderOptionChoice>(fixture.input.clone())
            }
            "ProviderOptionDescriptor" => {
                checked_roundtrip::<ProviderOptionDescriptor>(fixture.input.clone())
            }
            "ProviderOptionSelection" => {
                checked_roundtrip::<ProviderOptionSelection>(fixture.input.clone())
            }
            "ProviderOptionSelectionValue" => {
                checked_roundtrip::<ProviderOptionSelectionValue>(fixture.input.clone())
            }
            "ThreadLinkedPullRequest" => {
                checked_roundtrip::<ThreadLinkedPullRequest>(fixture.input.clone())
            }
            "ThreadPullRequestLink" => {
                checked_roundtrip::<ThreadPullRequestLink>(fixture.input.clone())
            }
            "ThreadPullRequestLinkSource" => {
                checked_roundtrip::<ThreadPullRequestLinkSource>(fixture.input.clone())
            }
            "ThreadPullRequestSnapshot" => {
                checked_roundtrip::<ThreadPullRequestSnapshot>(fixture.input.clone())
            }
            "ThreadPullRequestStack" => {
                checked_roundtrip::<ThreadPullRequestStack>(fixture.input.clone())
            }
            "ThreadPullRequestStackLayer" => {
                checked_roundtrip::<ThreadPullRequestStackLayer>(fixture.input.clone())
            }
            "ThreadPullRequestWatch" => {
                checked_roundtrip::<ThreadPullRequestWatch>(fixture.input.clone())
            }
            "ProviderSession" => checked_roundtrip::<ProviderSession>(fixture.input.clone()),
            "EnvironmentMachineKind" => {
                checked_roundtrip::<EnvironmentMachineKind>(fixture.input.clone())
            }
            "ExecutionEnvironmentCapabilities" => {
                checked_roundtrip::<ExecutionEnvironmentCapabilities>(fixture.input.clone())
            }
            "ExecutionEnvironmentDescriptor" => {
                checked_roundtrip::<ExecutionEnvironmentDescriptor>(fixture.input.clone())
            }
            "ExecutionEnvironmentPlatform" => {
                checked_roundtrip::<ExecutionEnvironmentPlatform>(fixture.input.clone())
            }
            "ExecutionEnvironmentPlatformArch" => {
                checked_roundtrip::<ExecutionEnvironmentPlatformArch>(fixture.input.clone())
            }
            "ExecutionEnvironmentPlatformOs" => {
                checked_roundtrip::<ExecutionEnvironmentPlatformOs>(fixture.input.clone())
            }
            "RepositoryIdentity" => checked_roundtrip::<RepositoryIdentity>(fixture.input.clone()),
            "RepositoryIdentityLocator" => {
                checked_roundtrip::<RepositoryIdentityLocator>(fixture.input.clone())
            }
            "RepositoryOrigin" => checked_roundtrip::<RepositoryOrigin>(fixture.input.clone()),
            "ScopedProjectRef" => checked_roundtrip::<ScopedProjectRef>(fixture.input.clone()),
            "ScopedThreadRef" => checked_roundtrip::<ScopedThreadRef>(fixture.input.clone()),
            "ServerInstallation" => checked_roundtrip::<ServerInstallation>(fixture.input.clone()),
            "ServerSelfUpdateCapability" => {
                checked_roundtrip::<ServerSelfUpdateCapability>(fixture.input.clone())
            }
            "ServerSelfUpdateMethod" => {
                checked_roundtrip::<ServerSelfUpdateMethod>(fixture.input.clone())
            }
            "ThreadEnvMode" => checked_roundtrip::<ThreadEnvMode>(fixture.input.clone()),
            "WorktreeSubmodules" => checked_roundtrip::<WorktreeSubmodules>(fixture.input.clone()),
            "ServerObservability" => {
                checked_roundtrip::<ServerObservability>(fixture.input.clone())
            }
            "ServerProvider" => checked_roundtrip::<ServerProvider>(fixture.input.clone()),
            "ServerProviderAuth" => checked_roundtrip::<ServerProviderAuth>(fixture.input.clone()),
            "ServerProviderAuthStatus" => {
                checked_roundtrip::<ServerProviderAuthStatus>(fixture.input.clone())
            }
            "ServerProviderAvailability" => {
                checked_roundtrip::<ServerProviderAvailability>(fixture.input.clone())
            }
            "ServerProviderCompatibilityAdvisory" => {
                checked_roundtrip::<ServerProviderCompatibilityAdvisory>(fixture.input.clone())
            }
            "ServerProviderCompatibilityStatus" => {
                checked_roundtrip::<ServerProviderCompatibilityStatus>(fixture.input.clone())
            }
            "ServerProviderContinuation" => {
                checked_roundtrip::<ServerProviderContinuation>(fixture.input.clone())
            }
            "ServerProviderModel" => {
                checked_roundtrip::<ServerProviderModel>(fixture.input.clone())
            }
            "ServerProviderSkill" => {
                checked_roundtrip::<ServerProviderSkill>(fixture.input.clone())
            }
            "ServerProviderSlashCommand" => {
                checked_roundtrip::<ServerProviderSlashCommand>(fixture.input.clone())
            }
            "ServerProviderSlashCommandInput" => {
                checked_roundtrip::<ServerProviderSlashCommandInput>(fixture.input.clone())
            }
            "ServerProviderState" => {
                checked_roundtrip::<ServerProviderState>(fixture.input.clone())
            }
            "ServerProviderUpdateState" => {
                checked_roundtrip::<ServerProviderUpdateState>(fixture.input.clone())
            }
            "ServerProviderUpdateStatus" => {
                checked_roundtrip::<ServerProviderUpdateStatus>(fixture.input.clone())
            }
            "ServerProviderVersionAdvisory" => {
                checked_roundtrip::<ServerProviderVersionAdvisory>(fixture.input.clone())
            }
            "ServerProviderVersionAdvisoryStatus" => {
                checked_roundtrip::<ServerProviderVersionAdvisoryStatus>(fixture.input.clone())
            }
            "ServerProviderWorkspaceSnapshot" => {
                checked_roundtrip::<ServerProviderWorkspaceSnapshot>(fixture.input.clone())
            }
            "ProviderUsageLimitsUpdate" => {
                checked_roundtrip::<ProviderUsageLimitsUpdate>(fixture.input.clone())
            }
            "ServerProviderResetCredits" => {
                checked_roundtrip::<ServerProviderResetCredits>(fixture.input.clone())
            }
            "ServerProviderUsageLimits" => {
                checked_roundtrip::<ServerProviderUsageLimits>(fixture.input.clone())
            }
            "ServerProviderUsageWindow" => {
                checked_roundtrip::<ServerProviderUsageWindow>(fixture.input.clone())
            }
            "AcpRegistryUrlAuthAction" => {
                checked_roundtrip::<AcpRegistryUrlAuthAction>(fixture.input.clone())
            }
            "ProviderRef" => checked_roundtrip::<ProviderRef>(fixture.input.clone()),
            "ProviderThreadNativeMetadata" => {
                checked_roundtrip::<ProviderThreadNativeMetadata>(fixture.input.clone())
            }
            "LimitRecovery" => checked_roundtrip::<LimitRecovery>(fixture.input.clone()),
            "LimitRecoveryUpdate" => {
                checked_roundtrip::<LimitRecoveryUpdate>(fixture.input.clone())
            }
            "PendingBackgroundTask" => {
                checked_roundtrip::<PendingBackgroundTask>(fixture.input.clone())
            }
            "ThreadForkSourcePoint" => {
                checked_roundtrip::<ThreadForkSourcePoint>(fixture.input.clone())
            }
            "ThreadCommand" => checked_roundtrip::<ThreadCommand>(fixture.input.clone()),
            // END ORIGINAL CODEC DISPATCH
            schema => panic!("unsupported fixture codec {schema}"),
        };
        if decoded_valid != fixture.decoded_valid.unwrap_or(fixture.valid)
            || result.is_ok() != fixture.valid
            || fixture.valid && result.as_ref().ok() != fixture.output.as_ref()
        {
            failures.push(format!(
                "{} input {}: Rust {:?}; original {:?}",
                fixture.schema, fixture.input, result, fixture.output
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
