//! Fixtures were generated by decoding and re-encoding the original Effect
//! contracts at packages/contracts/src/{baseSchemas,providerInstance,modelSelection}.ts.
use serde::{Deserialize, Serialize};
use serde_json::Value;
use t3_contracts::*;

#[derive(Deserialize)]
struct Fixture {
    schema: String,
    input: Value,
    valid: bool,
    output: Option<Value>,
}
fn roundtrip<T: serde::de::DeserializeOwned + Serialize>(
    value: Value,
) -> Result<Value, serde_json::Error> {
    serde_json::from_value::<T>(value).and_then(serde_json::to_value)
}

#[test]
fn rust_codecs_match_original_effect_decode_and_encode_fixtures() {
    let fixtures: Vec<Fixture> =
        serde_json::from_str(include_str!("fixtures/original-codecs.json")).unwrap();
    for fixture in fixtures {
        let result = match fixture.schema.as_str() {
            "ThreadId" => roundtrip::<ThreadId>(fixture.input.clone()),
            "ProviderDriverKind" => roundtrip::<ProviderDriverKind>(fixture.input.clone()),
            "ProviderInstanceId" => roundtrip::<ProviderInstanceId>(fixture.input.clone()),
            "ModelSelection" => roundtrip::<ModelSelection>(fixture.input.clone()),
            schema => panic!("unsupported fixture codec {schema}"),
        };
        assert_eq!(
            result.is_ok(),
            fixture.valid,
            "{} input: {}",
            fixture.schema,
            fixture.input
        );
        if fixture.valid {
            assert_eq!(
                result.unwrap(),
                fixture.output.unwrap(),
                "{} input: {}",
                fixture.schema,
                fixture.input
            );
        }
    }
}
