//! Fixtures were generated by decoding and re-encoding the original Effect
//! contracts at packages/contracts/src/{baseSchemas,providerInstance,modelSelection}.ts.
use serde::{Deserialize, Serialize};
use serde_json::Value;
use t3_contracts::*;

#[derive(Deserialize)]
struct Fixture {
    schema: String,
    input: Value,
    valid: bool,
    decoded_valid: Option<bool>,
    output: Option<Value>,
}
fn roundtrip<T: serde::de::DeserializeOwned + Serialize>(
    value: Value,
) -> Result<Value, serde_json::Error> {
    serde_json::from_value::<T>(value).and_then(serde_json::to_value)
}

#[test]
fn rust_codecs_match_original_effect_decode_and_encode_fixtures() {
    let fixtures: Vec<Fixture> =
        serde_json::from_str(include_str!("fixtures/original-codecs.json")).unwrap();
    for fixture in fixtures {
        let result = match fixture.schema.as_str() {
            "ThreadId" => roundtrip::<ThreadId>(fixture.input.clone()),
            "ProviderDriverKind" => roundtrip::<ProviderDriverKind>(fixture.input.clone()),
            "ProviderInstanceId" => roundtrip::<ProviderInstanceId>(fixture.input.clone()),
            "ModelSelection" => roundtrip::<ModelSelection>(fixture.input.clone()),
            schema => panic!("unsupported fixture codec {schema}"),
        };
        assert_eq!(
            result.is_ok(),
            fixture.valid,
            "{} input: {}",
            fixture.schema,
            fixture.input
        );
        if fixture.valid {
            assert_eq!(
                result.unwrap(),
                fixture.output.unwrap(),
                "{} input: {}",
                fixture.schema,
                fixture.input
            );
        }
    }
}

/// Generated by the original Schema.toCodecJson codecs, including each field's
/// missing/null/wrong-type behavior. These are reference outputs, not Rust snapshots.
#[test]
fn expanded_rust_codecs_match_original_json_wire_codecs() {
    fn checked_roundtrip<T: serde::de::DeserializeOwned + Serialize>(
        value: Value,
    ) -> (bool, Result<Value, serde_json::Error>) {
        match serde_json::from_value::<T>(value) {
            Ok(decoded) => (true, serde_json::to_value(decoded)),
            Err(error) => (false, Err(error)),
        }
    }
    let mut fixtures_json = String::new();
    std::io::Read::read_to_string(
        &mut flate2::read::GzDecoder::new(&include_bytes!("fixtures/expanded-codecs.jsonl.gz")[..]),
        &mut fixtures_json,
    )
    .unwrap();
    let fixtures: Vec<Fixture> = fixtures_json
        .lines()
        .map(|line| serde_json::from_str(line).unwrap())
        .collect();
    let mut failures = Vec::new();
    let mut counts = std::collections::BTreeMap::<String, usize>::new();
    for fixture in fixtures {
        let (decoded_valid, result) = match fixture.schema.as_str() {
            // BEGIN ORIGINAL CODEC DISPATCH
            "AuthAccessSnapshot" => checked_roundtrip::<AuthAccessSnapshot>(fixture.input.clone()),
            "AuthAccessStreamEvent" => {
                checked_roundtrip::<AuthAccessStreamEvent>(fixture.input.clone())
            }
            "AuthAccessTokenResult" => {
                checked_roundtrip::<AuthAccessTokenResult>(fixture.input.clone())
            }
            "AuthBrowserSessionRequest" => {
                checked_roundtrip::<AuthBrowserSessionRequest>(fixture.input.clone())
            }
            "AuthBrowserSessionResult" => {
                checked_roundtrip::<AuthBrowserSessionResult>(fixture.input.clone())
            }
            "AuthClientMetadata" => checked_roundtrip::<AuthClientMetadata>(fixture.input.clone()),
            "AuthClientMetadataDeviceType" => {
                checked_roundtrip::<AuthClientMetadataDeviceType>(fixture.input.clone())
            }
            "AuthClientPresentationMetadata" => {
                checked_roundtrip::<AuthClientPresentationMetadata>(fixture.input.clone())
            }
            "AuthClientSession" => checked_roundtrip::<AuthClientSession>(fixture.input.clone()),
            "AuthCreatePairingCredentialInput" => {
                checked_roundtrip::<AuthCreatePairingCredentialInput>(fixture.input.clone())
            }
            "AuthEnvironmentScope" => {
                checked_roundtrip::<AuthEnvironmentScope>(fixture.input.clone())
            }
            "AuthGrantScope" => checked_roundtrip::<AuthGrantScope>(fixture.input.clone()),
            "AuthMcpApprovalDecision" => {
                checked_roundtrip::<AuthMcpApprovalDecision>(fixture.input.clone())
            }
            "AuthMcpApprovalDecisionRequest" => {
                checked_roundtrip::<AuthMcpApprovalDecisionRequest>(fixture.input.clone())
            }
            "AuthMcpApprovalDetails" => {
                checked_roundtrip::<AuthMcpApprovalDetails>(fixture.input.clone())
            }
            "AuthMcpApprovalRedirect" => {
                checked_roundtrip::<AuthMcpApprovalRedirect>(fixture.input.clone())
            }
            "AuthMcpAuthorizationRequest" => {
                checked_roundtrip::<AuthMcpAuthorizationRequest>(fixture.input.clone())
            }
            "AuthMcpAuthorizationServerMetadata" => {
                checked_roundtrip::<AuthMcpAuthorizationServerMetadata>(fixture.input.clone())
            }
            "AuthMcpClientAccess" => {
                checked_roundtrip::<AuthMcpClientAccess>(fixture.input.clone())
            }
            "AuthMcpClientRegistration" => {
                checked_roundtrip::<AuthMcpClientRegistration>(fixture.input.clone())
            }
            "AuthMcpProtectedResourceMetadata" => {
                checked_roundtrip::<AuthMcpProtectedResourceMetadata>(fixture.input.clone())
            }
            "AuthMcpRegisteredClient" => {
                checked_roundtrip::<AuthMcpRegisteredClient>(fixture.input.clone())
            }
            "AuthMcpRegistrationError" => {
                checked_roundtrip::<AuthMcpRegistrationError>(fixture.input.clone())
            }
            "AuthMcpTokenError" => checked_roundtrip::<AuthMcpTokenError>(fixture.input.clone()),
            "AuthMcpTokenRequest" => {
                checked_roundtrip::<AuthMcpTokenRequest>(fixture.input.clone())
            }
            "AuthMcpTokenResult" => checked_roundtrip::<AuthMcpTokenResult>(fixture.input.clone()),
            "AuthPairingCredentialResult" => {
                checked_roundtrip::<AuthPairingCredentialResult>(fixture.input.clone())
            }
            "AuthPairingLink" => checked_roundtrip::<AuthPairingLink>(fixture.input.clone()),
            "AuthRevokeClientSessionInput" => {
                checked_roundtrip::<AuthRevokeClientSessionInput>(fixture.input.clone())
            }
            "AuthRevokePairingLinkInput" => {
                checked_roundtrip::<AuthRevokePairingLinkInput>(fixture.input.clone())
            }
            "AuthSessionState" => checked_roundtrip::<AuthSessionState>(fixture.input.clone()),
            "AuthTokenExchangeRequest" => {
                checked_roundtrip::<AuthTokenExchangeRequest>(fixture.input.clone())
            }
            "AuthWebSocketTicketResult" => {
                checked_roundtrip::<AuthWebSocketTicketResult>(fixture.input.clone())
            }
            "ServerAuthBootstrapMethod" => {
                checked_roundtrip::<ServerAuthBootstrapMethod>(fixture.input.clone())
            }
            "ServerAuthDescriptor" => {
                checked_roundtrip::<ServerAuthDescriptor>(fixture.input.clone())
            }
            "ServerAuthPolicy" => checked_roundtrip::<ServerAuthPolicy>(fixture.input.clone()),
            "ServerAuthSessionMethod" => {
                checked_roundtrip::<ServerAuthSessionMethod>(fixture.input.clone())
            }
            "ProviderInstanceConfig" => {
                checked_roundtrip::<ProviderInstanceConfig>(fixture.input.clone())
            }
            "ProviderInstanceConfigMap" => {
                checked_roundtrip::<ProviderInstanceConfigMap>(fixture.input.clone())
            }
            "ProviderInstanceEnvironmentVariable" => {
                checked_roundtrip::<ProviderInstanceEnvironmentVariable>(fixture.input.clone())
            }
            "ProviderInstanceMutation" => {
                checked_roundtrip::<ProviderInstanceMutation>(fixture.input.clone())
            }
            "ProviderInstanceRef" => {
                checked_roundtrip::<ProviderInstanceRef>(fixture.input.clone())
            }
            "CustomModelEntry" => checked_roundtrip::<CustomModelEntry>(fixture.input.clone()),
            "CustomModelSetting" => checked_roundtrip::<CustomModelSetting>(fixture.input.clone()),
            "ModelCapabilities" => checked_roundtrip::<ModelCapabilities>(fixture.input.clone()),
            "ProviderOptionChoice" => {
                checked_roundtrip::<ProviderOptionChoice>(fixture.input.clone())
            }
            "ProviderOptionDescriptor" => {
                checked_roundtrip::<ProviderOptionDescriptor>(fixture.input.clone())
            }
            "ProviderOptionSelection" => {
                checked_roundtrip::<ProviderOptionSelection>(fixture.input.clone())
            }
            "ProviderOptionSelectionValue" => {
                checked_roundtrip::<ProviderOptionSelectionValue>(fixture.input.clone())
            }
            "ProviderOptionSelections" => {
                checked_roundtrip::<ProviderOptionSelections>(fixture.input.clone())
            }
            "ThreadLinkedPullRequest" => {
                checked_roundtrip::<ThreadLinkedPullRequest>(fixture.input.clone())
            }
            "ThreadPullRequestLink" => {
                checked_roundtrip::<ThreadPullRequestLink>(fixture.input.clone())
            }
            "ThreadPullRequestLinkSource" => {
                checked_roundtrip::<ThreadPullRequestLinkSource>(fixture.input.clone())
            }
            "ThreadPullRequestSnapshot" => {
                checked_roundtrip::<ThreadPullRequestSnapshot>(fixture.input.clone())
            }
            "ThreadPullRequestStack" => {
                checked_roundtrip::<ThreadPullRequestStack>(fixture.input.clone())
            }
            "ThreadPullRequestStackLayer" => {
                checked_roundtrip::<ThreadPullRequestStackLayer>(fixture.input.clone())
            }
            "ThreadPullRequestWatch" => {
                checked_roundtrip::<ThreadPullRequestWatch>(fixture.input.clone())
            }
            "ProviderSession" => checked_roundtrip::<ProviderSession>(fixture.input.clone()),
            "EnvironmentMachineKind" => {
                checked_roundtrip::<EnvironmentMachineKind>(fixture.input.clone())
            }
            "ExecutionEnvironmentCapabilities" => {
                checked_roundtrip::<ExecutionEnvironmentCapabilities>(fixture.input.clone())
            }
            "ExecutionEnvironmentDescriptor" => {
                checked_roundtrip::<ExecutionEnvironmentDescriptor>(fixture.input.clone())
            }
            "ExecutionEnvironmentPlatform" => {
                checked_roundtrip::<ExecutionEnvironmentPlatform>(fixture.input.clone())
            }
            "ExecutionEnvironmentPlatformArch" => {
                checked_roundtrip::<ExecutionEnvironmentPlatformArch>(fixture.input.clone())
            }
            "ExecutionEnvironmentPlatformOs" => {
                checked_roundtrip::<ExecutionEnvironmentPlatformOs>(fixture.input.clone())
            }
            "RepositoryIdentity" => checked_roundtrip::<RepositoryIdentity>(fixture.input.clone()),
            "RepositoryIdentityLocator" => {
                checked_roundtrip::<RepositoryIdentityLocator>(fixture.input.clone())
            }
            "RepositoryOrigin" => checked_roundtrip::<RepositoryOrigin>(fixture.input.clone()),
            "ScopedProjectRef" => checked_roundtrip::<ScopedProjectRef>(fixture.input.clone()),
            "ScopedThreadRef" => checked_roundtrip::<ScopedThreadRef>(fixture.input.clone()),
            "ServerInstallation" => checked_roundtrip::<ServerInstallation>(fixture.input.clone()),
            "ServerSelfUpdateCapability" => {
                checked_roundtrip::<ServerSelfUpdateCapability>(fixture.input.clone())
            }
            "ServerSelfUpdateMethod" => {
                checked_roundtrip::<ServerSelfUpdateMethod>(fixture.input.clone())
            }
            "ThreadEnvMode" => checked_roundtrip::<ThreadEnvMode>(fixture.input.clone()),
            "WorktreeSubmodules" => checked_roundtrip::<WorktreeSubmodules>(fixture.input.clone()),
            "EnvironmentTheme" => checked_roundtrip::<EnvironmentTheme>(fixture.input.clone()),
            "EnvironmentThemeFile" => {
                checked_roundtrip::<EnvironmentThemeFile>(fixture.input.clone())
            }
            "ServerConfig" => checked_roundtrip::<ServerConfig>(fixture.input.clone()),
            "ServerConfigIssue" => checked_roundtrip::<ServerConfigIssue>(fixture.input.clone()),
            "ServerDirectEndpoint" => {
                checked_roundtrip::<ServerDirectEndpoint>(fixture.input.clone())
            }
            "ServerDirectEndpointKind" => {
                checked_roundtrip::<ServerDirectEndpointKind>(fixture.input.clone())
            }
            "ServerObservability" => {
                checked_roundtrip::<ServerObservability>(fixture.input.clone())
            }
            "ServerProvider" => checked_roundtrip::<ServerProvider>(fixture.input.clone()),
            "ServerProviderAuth" => checked_roundtrip::<ServerProviderAuth>(fixture.input.clone()),
            "ServerProviderAuthStatus" => {
                checked_roundtrip::<ServerProviderAuthStatus>(fixture.input.clone())
            }
            "ServerProviderAvailability" => {
                checked_roundtrip::<ServerProviderAvailability>(fixture.input.clone())
            }
            "ServerProviderCompatibilityAdvisory" => {
                checked_roundtrip::<ServerProviderCompatibilityAdvisory>(fixture.input.clone())
            }
            "ServerProviderCompatibilityStatus" => {
                checked_roundtrip::<ServerProviderCompatibilityStatus>(fixture.input.clone())
            }
            "ServerProviderContinuation" => {
                checked_roundtrip::<ServerProviderContinuation>(fixture.input.clone())
            }
            "ServerProviderModel" => {
                checked_roundtrip::<ServerProviderModel>(fixture.input.clone())
            }
            "ServerProviderSkill" => {
                checked_roundtrip::<ServerProviderSkill>(fixture.input.clone())
            }
            "ServerProviderSlashCommand" => {
                checked_roundtrip::<ServerProviderSlashCommand>(fixture.input.clone())
            }
            "ServerProviderSlashCommandInput" => {
                checked_roundtrip::<ServerProviderSlashCommandInput>(fixture.input.clone())
            }
            "ServerProviderState" => {
                checked_roundtrip::<ServerProviderState>(fixture.input.clone())
            }
            "ServerProviderUpdateState" => {
                checked_roundtrip::<ServerProviderUpdateState>(fixture.input.clone())
            }
            "ServerProviderUpdateStatus" => {
                checked_roundtrip::<ServerProviderUpdateStatus>(fixture.input.clone())
            }
            "ServerProviderVersionAdvisory" => {
                checked_roundtrip::<ServerProviderVersionAdvisory>(fixture.input.clone())
            }
            "ServerProviderVersionAdvisoryStatus" => {
                checked_roundtrip::<ServerProviderVersionAdvisoryStatus>(fixture.input.clone())
            }
            "ServerProviderWorkspaceSnapshot" => {
                checked_roundtrip::<ServerProviderWorkspaceSnapshot>(fixture.input.clone())
            }
            "ProviderUsageLimitsUpdate" => {
                checked_roundtrip::<ProviderUsageLimitsUpdate>(fixture.input.clone())
            }
            "ServerProviderResetCredits" => {
                checked_roundtrip::<ServerProviderResetCredits>(fixture.input.clone())
            }
            "ServerProviderUsageLimits" => {
                checked_roundtrip::<ServerProviderUsageLimits>(fixture.input.clone())
            }
            "ServerProviderUsageWindow" => {
                checked_roundtrip::<ServerProviderUsageWindow>(fixture.input.clone())
            }
            "UsageLimitSourceAccount" => {
                checked_roundtrip::<UsageLimitSourceAccount>(fixture.input.clone())
            }
            "UsageLimitSourceSnapshot" => {
                checked_roundtrip::<UsageLimitSourceSnapshot>(fixture.input.clone())
            }
            "AcpRegistryAcceptUrlAuthInput" => {
                checked_roundtrip::<AcpRegistryAcceptUrlAuthInput>(fixture.input.clone())
            }
            "AcpRegistryAcceptUrlAuthResult" => {
                checked_roundtrip::<AcpRegistryAcceptUrlAuthResult>(fixture.input.clone())
            }
            "AcpRegistryConfigurableProvider" => {
                checked_roundtrip::<AcpRegistryConfigurableProvider>(fixture.input.clone())
            }
            "AcpRegistryDeleteSessionInput" => {
                checked_roundtrip::<AcpRegistryDeleteSessionInput>(fixture.input.clone())
            }
            "AcpRegistryDeleteSessionResult" => {
                checked_roundtrip::<AcpRegistryDeleteSessionResult>(fixture.input.clone())
            }
            "AcpRegistryDisableProviderInput" => {
                checked_roundtrip::<AcpRegistryDisableProviderInput>(fixture.input.clone())
            }
            "AcpRegistryDisableProviderResult" => {
                checked_roundtrip::<AcpRegistryDisableProviderResult>(fixture.input.clone())
            }
            "AcpRegistryDistribution" => {
                checked_roundtrip::<AcpRegistryDistribution>(fixture.input.clone())
            }
            "AcpRegistryImportSessionInput" => {
                checked_roundtrip::<AcpRegistryImportSessionInput>(fixture.input.clone())
            }
            "AcpRegistryImportSessionResult" => {
                checked_roundtrip::<AcpRegistryImportSessionResult>(fixture.input.clone())
            }
            "AcpRegistryIntegrity" => {
                checked_roundtrip::<AcpRegistryIntegrity>(fixture.input.clone())
            }
            "AcpRegistryListProvidersInput" => {
                checked_roundtrip::<AcpRegistryListProvidersInput>(fixture.input.clone())
            }
            "AcpRegistryListProvidersResult" => {
                checked_roundtrip::<AcpRegistryListProvidersResult>(fixture.input.clone())
            }
            "AcpRegistryListSessionsInput" => {
                checked_roundtrip::<AcpRegistryListSessionsInput>(fixture.input.clone())
            }
            "AcpRegistryListSessionsResult" => {
                checked_roundtrip::<AcpRegistryListSessionsResult>(fixture.input.clone())
            }
            "AcpRegistryLogoutInput" => {
                checked_roundtrip::<AcpRegistryLogoutInput>(fixture.input.clone())
            }
            "AcpRegistryLogoutResult" => {
                checked_roundtrip::<AcpRegistryLogoutResult>(fixture.input.clone())
            }
            "AcpRegistryManagedBinaryUninstallInput" => {
                checked_roundtrip::<AcpRegistryManagedBinaryUninstallInput>(fixture.input.clone())
            }
            "AcpRegistryManagedBinaryUninstallResult" => {
                checked_roundtrip::<AcpRegistryManagedBinaryUninstallResult>(fixture.input.clone())
            }
            "AcpRegistryOperationError" => {
                checked_roundtrip::<AcpRegistryOperationError>(fixture.input.clone())
            }
            "AcpRegistryOperationErrorReason" => {
                checked_roundtrip::<AcpRegistryOperationErrorReason>(fixture.input.clone())
            }
            "AcpRegistryPrepareInput" => {
                checked_roundtrip::<AcpRegistryPrepareInput>(fixture.input.clone())
            }
            "AcpRegistryPrepareResult" => {
                checked_roundtrip::<AcpRegistryPrepareResult>(fixture.input.clone())
            }
            "AcpRegistryProbeAuthMethod" => {
                checked_roundtrip::<AcpRegistryProbeAuthMethod>(fixture.input.clone())
            }
            "AcpRegistryProbeModel" => {
                checked_roundtrip::<AcpRegistryProbeModel>(fixture.input.clone())
            }
            "AcpRegistryProbeResult" => {
                checked_roundtrip::<AcpRegistryProbeResult>(fixture.input.clone())
            }
            "AcpRegistrySearchAgent" => {
                checked_roundtrip::<AcpRegistrySearchAgent>(fixture.input.clone())
            }
            "AcpRegistrySearchInput" => {
                checked_roundtrip::<AcpRegistrySearchInput>(fixture.input.clone())
            }
            "AcpRegistrySearchResult" => {
                checked_roundtrip::<AcpRegistrySearchResult>(fixture.input.clone())
            }
            "AcpRegistrySession" => checked_roundtrip::<AcpRegistrySession>(fixture.input.clone()),
            "AcpRegistrySetProviderInput" => {
                checked_roundtrip::<AcpRegistrySetProviderInput>(fixture.input.clone())
            }
            "AcpRegistrySetProviderResult" => {
                checked_roundtrip::<AcpRegistrySetProviderResult>(fixture.input.clone())
            }
            "AcpRegistryUrlAuthAction" => {
                checked_roundtrip::<AcpRegistryUrlAuthAction>(fixture.input.clone())
            }
            "ChatGptHandoffInput" => {
                checked_roundtrip::<ChatGptHandoffInput>(fixture.input.clone())
            }
            "ChatGptHandoffState" => {
                checked_roundtrip::<ChatGptHandoffState>(fixture.input.clone())
            }
            "ChatGptImportProfileInput" => {
                checked_roundtrip::<ChatGptImportProfileInput>(fixture.input.clone())
            }
            "ChatGptReconnectProfile" => {
                checked_roundtrip::<ChatGptReconnectProfile>(fixture.input.clone())
            }
            "ChatGptReconnectProfileInput" => {
                checked_roundtrip::<ChatGptReconnectProfileInput>(fixture.input.clone())
            }
            "ChatGptTransferredProfile" => {
                checked_roundtrip::<ChatGptTransferredProfile>(fixture.input.clone())
            }
            "CodexAuthCallbackInput" => {
                checked_roundtrip::<CodexAuthCallbackInput>(fixture.input.clone())
            }
            "CodexAuthCallbackState" => {
                checked_roundtrip::<CodexAuthCallbackState>(fixture.input.clone())
            }
            "ProviderAuthCancelInput" => {
                checked_roundtrip::<ProviderAuthCancelInput>(fixture.input.clone())
            }
            "ProviderAuthCompleteInput" => {
                checked_roundtrip::<ProviderAuthCompleteInput>(fixture.input.clone())
            }
            "ProviderAuthInteraction" => {
                checked_roundtrip::<ProviderAuthInteraction>(fixture.input.clone())
            }
            "ProviderAuthMethod" => checked_roundtrip::<ProviderAuthMethod>(fixture.input.clone()),
            "ProviderAuthRespondInput" => {
                checked_roundtrip::<ProviderAuthRespondInput>(fixture.input.clone())
            }
            "ProviderAuthResponse" => {
                checked_roundtrip::<ProviderAuthResponse>(fixture.input.clone())
            }
            "ProviderAuthStartInput" => {
                checked_roundtrip::<ProviderAuthStartInput>(fixture.input.clone())
            }
            "ProviderAuthState" => checked_roundtrip::<ProviderAuthState>(fixture.input.clone()),
            "ProviderInstallCancelInput" => {
                checked_roundtrip::<ProviderInstallCancelInput>(fixture.input.clone())
            }
            "ProviderInstallState" => {
                checked_roundtrip::<ProviderInstallState>(fixture.input.clone())
            }
            "ProviderSetupError" => checked_roundtrip::<ProviderSetupError>(fixture.input.clone()),
            "ProviderSetupInput" => checked_roundtrip::<ProviderSetupInput>(fixture.input.clone()),
            "AcpRegistryDistributionPreference" => {
                checked_roundtrip::<AcpRegistryDistributionPreference>(fixture.input.clone())
            }
            "AcpRegistrySettings" => {
                checked_roundtrip::<AcpRegistrySettings>(fixture.input.clone())
            }
            "AntigravityAuthMethod" => {
                checked_roundtrip::<AntigravityAuthMethod>(fixture.input.clone())
            }
            "AntigravitySettings" => {
                checked_roundtrip::<AntigravitySettings>(fixture.input.clone())
            }
            "BackgroundActivityOverrides" => {
                checked_roundtrip::<BackgroundActivityOverrides>(fixture.input.clone())
            }
            "BackgroundActivityProfile" => {
                checked_roundtrip::<BackgroundActivityProfile>(fixture.input.clone())
            }
            "BackgroundActivityProfileSelection" => {
                checked_roundtrip::<BackgroundActivityProfileSelection>(fixture.input.clone())
            }
            "BackgroundActivitySettings" => {
                checked_roundtrip::<BackgroundActivitySettings>(fixture.input.clone())
            }
            "BitbucketSettings" => checked_roundtrip::<BitbucketSettings>(fixture.input.clone()),
            "BranchNamingMode" => checked_roundtrip::<BranchNamingMode>(fixture.input.clone()),
            "ClaudeSettings" => checked_roundtrip::<ClaudeSettings>(fixture.input.clone()),
            "CodexSettings" => checked_roundtrip::<CodexSettings>(fixture.input.clone()),
            "CursorSettings" => checked_roundtrip::<CursorSettings>(fixture.input.clone()),
            "GitHubHost" => checked_roundtrip::<GitHubHost>(fixture.input.clone()),
            "GitHubHostSettings" => checked_roundtrip::<GitHubHostSettings>(fixture.input.clone()),
            "GitHubSettings" => checked_roundtrip::<GitHubSettings>(fixture.input.clone()),
            "GrokSettings" => checked_roundtrip::<GrokSettings>(fixture.input.clone()),
            "ObservabilitySettings" => {
                checked_roundtrip::<ObservabilitySettings>(fixture.input.clone())
            }
            "OpenCodeSettings" => checked_roundtrip::<OpenCodeSettings>(fixture.input.clone()),
            "PiSettings" => checked_roundtrip::<PiSettings>(fixture.input.clone()),
            "ProjectSettingsOverrides" => {
                checked_roundtrip::<ProjectSettingsOverrides>(fixture.input.clone())
            }
            "ResponseStreamingMode" => {
                checked_roundtrip::<ResponseStreamingMode>(fixture.input.clone())
            }
            "ServerSettings" => checked_roundtrip::<ServerSettings>(fixture.input.clone()),
            "ServerSettingsPatch" => {
                checked_roundtrip::<ServerSettingsPatch>(fixture.input.clone())
            }
            "SidebarAutoSettleAfterDays" => {
                checked_roundtrip::<SidebarAutoSettleAfterDays>(fixture.input.clone())
            }
            "SourceControlWritingStyleMode" => {
                checked_roundtrip::<SourceControlWritingStyleMode>(fixture.input.clone())
            }
            "SourceControlWritingStyleSettings" => {
                checked_roundtrip::<SourceControlWritingStyleSettings>(fixture.input.clone())
            }
            "StorageCleanupSettings" => {
                checked_roundtrip::<StorageCleanupSettings>(fixture.input.clone())
            }
            "UsageLimitSourceConfig" => {
                checked_roundtrip::<UsageLimitSourceConfig>(fixture.input.clone())
            }
            "UsageModelPriceOverride" => {
                checked_roundtrip::<UsageModelPriceOverride>(fixture.input.clone())
            }
            "WorktreeCleanup" => checked_roundtrip::<WorktreeCleanup>(fixture.input.clone()),
            "WorktreeCleanupRules" => {
                checked_roundtrip::<WorktreeCleanupRules>(fixture.input.clone())
            }
            "SshDeviceHostConfig" => {
                checked_roundtrip::<SshDeviceHostConfig>(fixture.input.clone())
            }
            "SshDeviceHostConfigs" => {
                checked_roundtrip::<SshDeviceHostConfigs>(fixture.input.clone())
            }
            "ProjectContentMatch" => {
                checked_roundtrip::<ProjectContentMatch>(fixture.input.clone())
            }
            "ProjectContentMatchRange" => {
                checked_roundtrip::<ProjectContentMatchRange>(fixture.input.clone())
            }
            "ProjectCreateNewInput" => {
                checked_roundtrip::<ProjectCreateNewInput>(fixture.input.clone())
            }
            "ProjectCreateNewResult" => {
                checked_roundtrip::<ProjectCreateNewResult>(fixture.input.clone())
            }
            "ProjectEnsureScratchResult" => {
                checked_roundtrip::<ProjectEnsureScratchResult>(fixture.input.clone())
            }
            "ProjectEntriesFailure" => {
                checked_roundtrip::<ProjectEntriesFailure>(fixture.input.clone())
            }
            "ProjectEntry" => checked_roundtrip::<ProjectEntry>(fixture.input.clone()),
            "ProjectEntryKind" => checked_roundtrip::<ProjectEntryKind>(fixture.input.clone()),
            "ProjectFileFailure" => checked_roundtrip::<ProjectFileFailure>(fixture.input.clone()),
            "ProjectFileOperation" => {
                checked_roundtrip::<ProjectFileOperation>(fixture.input.clone())
            }
            "ProjectListEntriesError" => {
                checked_roundtrip::<ProjectListEntriesError>(fixture.input.clone())
            }
            "ProjectListEntriesInput" => {
                checked_roundtrip::<ProjectListEntriesInput>(fixture.input.clone())
            }
            "ProjectListEntriesResult" => {
                checked_roundtrip::<ProjectListEntriesResult>(fixture.input.clone())
            }
            "ProjectReadFileError" => {
                checked_roundtrip::<ProjectReadFileError>(fixture.input.clone())
            }
            "ProjectReadFileInput" => {
                checked_roundtrip::<ProjectReadFileInput>(fixture.input.clone())
            }
            "ProjectReadFileResult" => {
                checked_roundtrip::<ProjectReadFileResult>(fixture.input.clone())
            }
            "ProjectScript" => checked_roundtrip::<ProjectScript>(fixture.input.clone()),
            "ProjectScriptIcon" => checked_roundtrip::<ProjectScriptIcon>(fixture.input.clone()),
            "ProjectSearchContentsError" => {
                checked_roundtrip::<ProjectSearchContentsError>(fixture.input.clone())
            }
            "ProjectSearchContentsInput" => {
                checked_roundtrip::<ProjectSearchContentsInput>(fixture.input.clone())
            }
            "ProjectSearchContentsResult" => {
                checked_roundtrip::<ProjectSearchContentsResult>(fixture.input.clone())
            }
            "ProjectSearchEntriesError" => {
                checked_roundtrip::<ProjectSearchEntriesError>(fixture.input.clone())
            }
            "ProjectSearchEntriesInput" => {
                checked_roundtrip::<ProjectSearchEntriesInput>(fixture.input.clone())
            }
            "ProjectSearchEntriesResult" => {
                checked_roundtrip::<ProjectSearchEntriesResult>(fixture.input.clone())
            }
            "ProjectWriteFileError" => {
                checked_roundtrip::<ProjectWriteFileError>(fixture.input.clone())
            }
            "ProjectWriteFileInput" => {
                checked_roundtrip::<ProjectWriteFileInput>(fixture.input.clone())
            }
            "ProjectWriteFileResult" => {
                checked_roundtrip::<ProjectWriteFileResult>(fixture.input.clone())
            }
            "KeybindingRule" => checked_roundtrip::<KeybindingRule>(fixture.input.clone()),
            "KeybindingShortcut" => checked_roundtrip::<KeybindingShortcut>(fixture.input.clone()),
            "KeybindingWhenNode" => checked_roundtrip::<KeybindingWhenNode>(fixture.input.clone()),
            "KeybindingsConfig" => checked_roundtrip::<KeybindingsConfig>(fixture.input.clone()),
            "PreviewForwardedShortcut" => {
                checked_roundtrip::<PreviewForwardedShortcut>(fixture.input.clone())
            }
            "ResolvedKeybindingRule" => {
                checked_roundtrip::<ResolvedKeybindingRule>(fixture.input.clone())
            }
            "ResolvedKeybindingsConfig" => {
                checked_roundtrip::<ResolvedKeybindingsConfig>(fixture.input.clone())
            }
            "EditorId" => checked_roundtrip::<EditorId>(fixture.input.clone()),
            "FileManagerRevealKind" => {
                checked_roundtrip::<FileManagerRevealKind>(fixture.input.clone())
            }
            "RemoteOpenTarget" => checked_roundtrip::<RemoteOpenTarget>(fixture.input.clone()),
            "RemoteOpenTargetKind" => {
                checked_roundtrip::<RemoteOpenTargetKind>(fixture.input.clone())
            }
            "ChatAttachment" => checked_roundtrip::<ChatAttachment>(fixture.input.clone()),
            "ChatFileAttachment" => checked_roundtrip::<ChatFileAttachment>(fixture.input.clone()),
            "ChatImageAttachment" => {
                checked_roundtrip::<ChatImageAttachment>(fixture.input.clone())
            }
            "ChatUnknownAttachment" => {
                checked_roundtrip::<ChatUnknownAttachment>(fixture.input.clone())
            }
            "PastedTextAttachmentSource" => {
                checked_roundtrip::<PastedTextAttachmentSource>(fixture.input.clone())
            }
            "PersistChatAttachmentsInput" => {
                checked_roundtrip::<PersistChatAttachmentsInput>(fixture.input.clone())
            }
            "PersistChatAttachmentsResult" => {
                checked_roundtrip::<PersistChatAttachmentsResult>(fixture.input.clone())
            }
            "SnapShotAccessibility" => {
                checked_roundtrip::<SnapShotAccessibility>(fixture.input.clone())
            }
            "SnapShotAccessibilityNode" => {
                checked_roundtrip::<SnapShotAccessibilityNode>(fixture.input.clone())
            }
            "SnapShotSource" => checked_roundtrip::<SnapShotSource>(fixture.input.clone()),
            "UploadChatAttachment" => {
                checked_roundtrip::<UploadChatAttachment>(fixture.input.clone())
            }
            "UploadChatImageAttachment" => {
                checked_roundtrip::<UploadChatImageAttachment>(fixture.input.clone())
            }
            "ComposerContextRecord" => {
                checked_roundtrip::<ComposerContextRecord>(fixture.input.clone())
            }
            "ElementContextDetails" => {
                checked_roundtrip::<ElementContextDetails>(fixture.input.clone())
            }
            "ElementContextRecord" => {
                checked_roundtrip::<ElementContextRecord>(fixture.input.clone())
            }
            "ElementContextSource" => {
                checked_roundtrip::<ElementContextSource>(fixture.input.clone())
            }
            "FileContextRecord" => checked_roundtrip::<FileContextRecord>(fixture.input.clone()),
            "ImageContextRecord" => checked_roundtrip::<ImageContextRecord>(fixture.input.clone()),
            "KnownComposerContextRecord" => {
                checked_roundtrip::<KnownComposerContextRecord>(fixture.input.clone())
            }
            "MentionContextRecord" => {
                checked_roundtrip::<MentionContextRecord>(fixture.input.clone())
            }
            "OrchestrationMessageContext" => {
                checked_roundtrip::<OrchestrationMessageContext>(fixture.input.clone())
            }
            "PreviewAnnotationContextRecord" => {
                checked_roundtrip::<PreviewAnnotationContextRecord>(fixture.input.clone())
            }
            "PullRequestContextMetadata" => {
                checked_roundtrip::<PullRequestContextMetadata>(fixture.input.clone())
            }
            "ReviewCommentContextRecord" => {
                checked_roundtrip::<ReviewCommentContextRecord>(fixture.input.clone())
            }
            "SkillContextRecord" => checked_roundtrip::<SkillContextRecord>(fixture.input.clone()),
            "TerminalContextRecord" => {
                checked_roundtrip::<TerminalContextRecord>(fixture.input.clone())
            }
            "ThreadContextRecord" => {
                checked_roundtrip::<ThreadContextRecord>(fixture.input.clone())
            }
            "UnknownContextRecord" => {
                checked_roundtrip::<UnknownContextRecord>(fixture.input.clone())
            }
            "CanonicalItemType" => checked_roundtrip::<CanonicalItemType>(fixture.input.clone()),
            "CanonicalRequestType" => {
                checked_roundtrip::<CanonicalRequestType>(fixture.input.clone())
            }
            "ItemLifecyclePayload" => {
                checked_roundtrip::<ItemLifecyclePayload>(fixture.input.clone())
            }
            "ProviderRuntimeEvent" => {
                checked_roundtrip::<ProviderRuntimeEvent>(fixture.input.clone())
            }
            "ProviderRuntimeEventV2" => {
                checked_roundtrip::<ProviderRuntimeEventV2>(fixture.input.clone())
            }
            "ProviderRuntimeTurnStatus" => {
                checked_roundtrip::<ProviderRuntimeTurnStatus>(fixture.input.clone())
            }
            "RuntimeEventRaw" => checked_roundtrip::<RuntimeEventRaw>(fixture.input.clone()),
            "RuntimeTaskStatus" => checked_roundtrip::<RuntimeTaskStatus>(fixture.input.clone()),
            "RuntimeTaskUsage" => checked_roundtrip::<RuntimeTaskUsage>(fixture.input.clone()),
            "TaskAgentLinkage" => checked_roundtrip::<TaskAgentLinkage>(fixture.input.clone()),
            "TaskRunHandles" => checked_roundtrip::<TaskRunHandles>(fixture.input.clone()),
            "TaskWorkflowPhase" => checked_roundtrip::<TaskWorkflowPhase>(fixture.input.clone()),
            "ThreadTokenUsageSnapshot" => {
                checked_roundtrip::<ThreadTokenUsageSnapshot>(fixture.input.clone())
            }
            "ToolActivityIcon" => checked_roundtrip::<ToolActivityIcon>(fixture.input.clone()),
            "ToolActivityNativeAppReference" => {
                checked_roundtrip::<ToolActivityNativeAppReference>(fixture.input.clone())
            }
            "ToolActivitySource" => checked_roundtrip::<ToolActivitySource>(fixture.input.clone()),
            "ToolActivitySurface" => {
                checked_roundtrip::<ToolActivitySurface>(fixture.input.clone())
            }
            "ToolLifecycleItemType" => {
                checked_roundtrip::<ToolLifecycleItemType>(fixture.input.clone())
            }
            "TurnTokenUsage" => checked_roundtrip::<TurnTokenUsage>(fixture.input.clone()),
            "UserInputQuestion" => checked_roundtrip::<UserInputQuestion>(fixture.input.clone()),
            "UserInputRequestedPayload" => {
                checked_roundtrip::<UserInputRequestedPayload>(fixture.input.clone())
            }
            "ProviderApprovalDecision" => {
                checked_roundtrip::<ProviderApprovalDecision>(fixture.input.clone())
            }
            "ProviderApprovalOption" => {
                checked_roundtrip::<ProviderApprovalOption>(fixture.input.clone())
            }
            "ProviderApprovalPolicy" => {
                checked_roundtrip::<ProviderApprovalPolicy>(fixture.input.clone())
            }
            "ProviderInteractionMode" => {
                checked_roundtrip::<ProviderInteractionMode>(fixture.input.clone())
            }
            "ProviderRequestKind" => {
                checked_roundtrip::<ProviderRequestKind>(fixture.input.clone())
            }
            "ProviderSandboxMode" => {
                checked_roundtrip::<ProviderSandboxMode>(fixture.input.clone())
            }
            "ProviderUserInputAnswers" => {
                checked_roundtrip::<ProviderUserInputAnswers>(fixture.input.clone())
            }
            "RuntimeMode" => checked_roundtrip::<RuntimeMode>(fixture.input.clone()),
            "UserInputAttachmentAnswerPayload" => {
                checked_roundtrip::<UserInputAttachmentAnswerPayload>(fixture.input.clone())
            }
            "UserInputAttachments" => {
                checked_roundtrip::<UserInputAttachments>(fixture.input.clone())
            }
            "FilesystemBrowseEntry" => {
                checked_roundtrip::<FilesystemBrowseEntry>(fixture.input.clone())
            }
            "FilesystemBrowseError" => {
                checked_roundtrip::<FilesystemBrowseError>(fixture.input.clone())
            }
            "FilesystemBrowseFailure" => {
                checked_roundtrip::<FilesystemBrowseFailure>(fixture.input.clone())
            }
            "FilesystemBrowseInput" => {
                checked_roundtrip::<FilesystemBrowseInput>(fixture.input.clone())
            }
            "FilesystemBrowseResult" => {
                checked_roundtrip::<FilesystemBrowseResult>(fixture.input.clone())
            }
            "TerminalAttachInput" => {
                checked_roundtrip::<TerminalAttachInput>(fixture.input.clone())
            }
            "TerminalAttachStreamEvent" => {
                checked_roundtrip::<TerminalAttachStreamEvent>(fixture.input.clone())
            }
            "TerminalClearInput" => checked_roundtrip::<TerminalClearInput>(fixture.input.clone()),
            "TerminalCloseInput" => checked_roundtrip::<TerminalCloseInput>(fixture.input.clone()),
            "TerminalCwdError" => checked_roundtrip::<TerminalCwdError>(fixture.input.clone()),
            "TerminalCwdNotDirectoryError" => {
                checked_roundtrip::<TerminalCwdNotDirectoryError>(fixture.input.clone())
            }
            "TerminalCwdNotFoundError" => {
                checked_roundtrip::<TerminalCwdNotFoundError>(fixture.input.clone())
            }
            "TerminalCwdStatError" => {
                checked_roundtrip::<TerminalCwdStatError>(fixture.input.clone())
            }
            "TerminalError" => checked_roundtrip::<TerminalError>(fixture.input.clone()),
            "TerminalEvent" => checked_roundtrip::<TerminalEvent>(fixture.input.clone()),
            "TerminalHistoryError" => {
                checked_roundtrip::<TerminalHistoryError>(fixture.input.clone())
            }
            "TerminalMetadataStreamEvent" => {
                checked_roundtrip::<TerminalMetadataStreamEvent>(fixture.input.clone())
            }
            "TerminalNotRunningError" => {
                checked_roundtrip::<TerminalNotRunningError>(fixture.input.clone())
            }
            "TerminalObserveInput" => {
                checked_roundtrip::<TerminalObserveInput>(fixture.input.clone())
            }
            "TerminalOpenInput" => checked_roundtrip::<TerminalOpenInput>(fixture.input.clone()),
            "TerminalProviderEnvironmentError" => {
                checked_roundtrip::<TerminalProviderEnvironmentError>(fixture.input.clone())
            }
            "TerminalProviderInstanceNotFoundError" => {
                checked_roundtrip::<TerminalProviderInstanceNotFoundError>(fixture.input.clone())
            }
            "TerminalResizeError" => {
                checked_roundtrip::<TerminalResizeError>(fixture.input.clone())
            }
            "TerminalResizeInput" => {
                checked_roundtrip::<TerminalResizeInput>(fixture.input.clone())
            }
            "TerminalRestartInput" => {
                checked_roundtrip::<TerminalRestartInput>(fixture.input.clone())
            }
            "TerminalSessionLookupError" => {
                checked_roundtrip::<TerminalSessionLookupError>(fixture.input.clone())
            }
            "TerminalSessionSnapshot" => {
                checked_roundtrip::<TerminalSessionSnapshot>(fixture.input.clone())
            }
            "TerminalSessionStatus" => {
                checked_roundtrip::<TerminalSessionStatus>(fixture.input.clone())
            }
            "TerminalSummary" => checked_roundtrip::<TerminalSummary>(fixture.input.clone()),
            "TerminalThreadInput" => {
                checked_roundtrip::<TerminalThreadInput>(fixture.input.clone())
            }
            "TerminalWriteError" => checked_roundtrip::<TerminalWriteError>(fixture.input.clone()),
            "TerminalWriteInput" => checked_roundtrip::<TerminalWriteInput>(fixture.input.clone()),
            "PickedElementPayload" => {
                checked_roundtrip::<PickedElementPayload>(fixture.input.clone())
            }
            "PickedElementStackFrame" => {
                checked_roundtrip::<PickedElementStackFrame>(fixture.input.clone())
            }
            "PreviewAnnotationElementTarget" => {
                checked_roundtrip::<PreviewAnnotationElementTarget>(fixture.input.clone())
            }
            "PreviewAnnotationPayload" => {
                checked_roundtrip::<PreviewAnnotationPayload>(fixture.input.clone())
            }
            "PreviewAnnotationPoint" => {
                checked_roundtrip::<PreviewAnnotationPoint>(fixture.input.clone())
            }
            "PreviewAnnotationRect" => {
                checked_roundtrip::<PreviewAnnotationRect>(fixture.input.clone())
            }
            "PreviewAnnotationRegionTarget" => {
                checked_roundtrip::<PreviewAnnotationRegionTarget>(fixture.input.clone())
            }
            "PreviewAnnotationScreenshot" => {
                checked_roundtrip::<PreviewAnnotationScreenshot>(fixture.input.clone())
            }
            "PreviewAnnotationStrokeTarget" => {
                checked_roundtrip::<PreviewAnnotationStrokeTarget>(fixture.input.clone())
            }
            "PreviewAnnotationCaptureStyleChange" => {
                checked_roundtrip::<PreviewAnnotationCaptureStyleChange>(fixture.input.clone())
            }
            "PreviewAnnotationSubmission" => {
                checked_roundtrip::<PreviewAnnotationSubmission>(fixture.input.clone())
            }
            "ProviderRuntimeSessionStartedEvent" => {
                checked_roundtrip::<ProviderRuntimeSessionStartedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeSessionConfiguredEvent" => {
                checked_roundtrip::<ProviderRuntimeSessionConfiguredEvent>(fixture.input.clone())
            }
            "ProviderRuntimeSessionStateChangedEvent" => {
                checked_roundtrip::<ProviderRuntimeSessionStateChangedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeSessionExitedEvent" => {
                checked_roundtrip::<ProviderRuntimeSessionExitedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeThreadStartedEvent" => {
                checked_roundtrip::<ProviderRuntimeThreadStartedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeThreadStateChangedEvent" => {
                checked_roundtrip::<ProviderRuntimeThreadStateChangedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeThreadMetadataUpdatedEvent" => checked_roundtrip::<
                ProviderRuntimeThreadMetadataUpdatedEvent,
            >(fixture.input.clone()),
            "ProviderRuntimeThreadTokenUsageUpdatedEvent" => checked_roundtrip::<
                ProviderRuntimeThreadTokenUsageUpdatedEvent,
            >(fixture.input.clone()),
            "ProviderRuntimeThreadRealtimeStartedEvent" => checked_roundtrip::<
                ProviderRuntimeThreadRealtimeStartedEvent,
            >(fixture.input.clone()),
            "ProviderRuntimeThreadRealtimeItemAddedEvent" => checked_roundtrip::<
                ProviderRuntimeThreadRealtimeItemAddedEvent,
            >(fixture.input.clone()),
            "ProviderRuntimeThreadRealtimeAudioDeltaEvent" => checked_roundtrip::<
                ProviderRuntimeThreadRealtimeAudioDeltaEvent,
            >(fixture.input.clone()),
            "ProviderRuntimeThreadRealtimeErrorEvent" => {
                checked_roundtrip::<ProviderRuntimeThreadRealtimeErrorEvent>(fixture.input.clone())
            }
            "ProviderRuntimeThreadRealtimeClosedEvent" => {
                checked_roundtrip::<ProviderRuntimeThreadRealtimeClosedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeTurnStartedEvent" => {
                checked_roundtrip::<ProviderRuntimeTurnStartedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeTurnCompletedEvent" => {
                checked_roundtrip::<ProviderRuntimeTurnCompletedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeTurnAbortedEvent" => {
                checked_roundtrip::<ProviderRuntimeTurnAbortedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeTurnPlanUpdatedEvent" => {
                checked_roundtrip::<ProviderRuntimeTurnPlanUpdatedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeTurnProposedDeltaEvent" => {
                checked_roundtrip::<ProviderRuntimeTurnProposedDeltaEvent>(fixture.input.clone())
            }
            "ProviderRuntimeTurnProposedCompletedEvent" => checked_roundtrip::<
                ProviderRuntimeTurnProposedCompletedEvent,
            >(fixture.input.clone()),
            "ProviderRuntimeTurnDiffUpdatedEvent" => {
                checked_roundtrip::<ProviderRuntimeTurnDiffUpdatedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeItemStartedEvent" => {
                checked_roundtrip::<ProviderRuntimeItemStartedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeItemUpdatedEvent" => {
                checked_roundtrip::<ProviderRuntimeItemUpdatedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeItemCompletedEvent" => {
                checked_roundtrip::<ProviderRuntimeItemCompletedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeContentDeltaEvent" => {
                checked_roundtrip::<ProviderRuntimeContentDeltaEvent>(fixture.input.clone())
            }
            "ProviderRuntimeRequestOpenedEvent" => {
                checked_roundtrip::<ProviderRuntimeRequestOpenedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeRequestResolvedEvent" => {
                checked_roundtrip::<ProviderRuntimeRequestResolvedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeUserInputRequestedEvent" => {
                checked_roundtrip::<ProviderRuntimeUserInputRequestedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeUserInputResolvedEvent" => {
                checked_roundtrip::<ProviderRuntimeUserInputResolvedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeTaskStartedEvent" => {
                checked_roundtrip::<ProviderRuntimeTaskStartedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeTaskProgressEvent" => {
                checked_roundtrip::<ProviderRuntimeTaskProgressEvent>(fixture.input.clone())
            }
            "ProviderRuntimeTaskUpdatedEvent" => {
                checked_roundtrip::<ProviderRuntimeTaskUpdatedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeTaskCompletedEvent" => {
                checked_roundtrip::<ProviderRuntimeTaskCompletedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeHookStartedEvent" => {
                checked_roundtrip::<ProviderRuntimeHookStartedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeHookProgressEvent" => {
                checked_roundtrip::<ProviderRuntimeHookProgressEvent>(fixture.input.clone())
            }
            "ProviderRuntimeHookCompletedEvent" => {
                checked_roundtrip::<ProviderRuntimeHookCompletedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeToolProgressEvent" => {
                checked_roundtrip::<ProviderRuntimeToolProgressEvent>(fixture.input.clone())
            }
            "ProviderRuntimeToolSummaryEvent" => {
                checked_roundtrip::<ProviderRuntimeToolSummaryEvent>(fixture.input.clone())
            }
            "ProviderRuntimeAuthStatusEvent" => {
                checked_roundtrip::<ProviderRuntimeAuthStatusEvent>(fixture.input.clone())
            }
            "ProviderRuntimeAccountUpdatedEvent" => {
                checked_roundtrip::<ProviderRuntimeAccountUpdatedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeAccountRateLimitsUpdatedEvent" => checked_roundtrip::<
                ProviderRuntimeAccountRateLimitsUpdatedEvent,
            >(fixture.input.clone()),
            "ProviderRuntimeMcpStatusUpdatedEvent" => {
                checked_roundtrip::<ProviderRuntimeMcpStatusUpdatedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeMcpOauthCompletedEvent" => {
                checked_roundtrip::<ProviderRuntimeMcpOauthCompletedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeModelReroutedEvent" => {
                checked_roundtrip::<ProviderRuntimeModelReroutedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeConfigWarningEvent" => {
                checked_roundtrip::<ProviderRuntimeConfigWarningEvent>(fixture.input.clone())
            }
            "ProviderRuntimeDeprecationNoticeEvent" => {
                checked_roundtrip::<ProviderRuntimeDeprecationNoticeEvent>(fixture.input.clone())
            }
            "ProviderRuntimeFilesPersistedEvent" => {
                checked_roundtrip::<ProviderRuntimeFilesPersistedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeToolDeniedEvent" => {
                checked_roundtrip::<ProviderRuntimeToolDeniedEvent>(fixture.input.clone())
            }
            "ProviderRuntimeWarningEvent" => {
                checked_roundtrip::<ProviderRuntimeWarningEvent>(fixture.input.clone())
            }
            "ProviderRuntimeErrorEvent" => {
                checked_roundtrip::<ProviderRuntimeErrorEvent>(fixture.input.clone())
            }
            "SessionStartedPayload" => {
                checked_roundtrip::<SessionStartedPayload>(fixture.input.clone())
            }
            "SessionConfiguredPayload" => {
                checked_roundtrip::<SessionConfiguredPayload>(fixture.input.clone())
            }
            "SessionStateChangedPayload" => {
                checked_roundtrip::<SessionStateChangedPayload>(fixture.input.clone())
            }
            "SessionExitedPayload" => {
                checked_roundtrip::<SessionExitedPayload>(fixture.input.clone())
            }
            "ThreadStartedPayload" => {
                checked_roundtrip::<ThreadStartedPayload>(fixture.input.clone())
            }
            "ThreadStateChangedPayload" => {
                checked_roundtrip::<ThreadStateChangedPayload>(fixture.input.clone())
            }
            "ThreadMetadataUpdatedPayload" => {
                checked_roundtrip::<ThreadMetadataUpdatedPayload>(fixture.input.clone())
            }
            "ThreadTokenUsageUpdatedPayload" => {
                checked_roundtrip::<ThreadTokenUsageUpdatedPayload>(fixture.input.clone())
            }
            "ThreadRealtimeStartedPayload" => {
                checked_roundtrip::<ThreadRealtimeStartedPayload>(fixture.input.clone())
            }
            "ThreadRealtimeItemAddedPayload" => {
                checked_roundtrip::<ThreadRealtimeItemAddedPayload>(fixture.input.clone())
            }
            "ThreadRealtimeAudioDeltaPayload" => {
                checked_roundtrip::<ThreadRealtimeAudioDeltaPayload>(fixture.input.clone())
            }
            "ThreadRealtimeErrorPayload" => {
                checked_roundtrip::<ThreadRealtimeErrorPayload>(fixture.input.clone())
            }
            "ThreadRealtimeClosedPayload" => {
                checked_roundtrip::<ThreadRealtimeClosedPayload>(fixture.input.clone())
            }
            "TurnStartedPayload" => checked_roundtrip::<TurnStartedPayload>(fixture.input.clone()),
            "TurnCompletedPayload" => {
                checked_roundtrip::<TurnCompletedPayload>(fixture.input.clone())
            }
            "TurnAbortedPayload" => checked_roundtrip::<TurnAbortedPayload>(fixture.input.clone()),
            "TurnPlanUpdatedPayload" => {
                checked_roundtrip::<TurnPlanUpdatedPayload>(fixture.input.clone())
            }
            "TurnProposedDeltaPayload" => {
                checked_roundtrip::<TurnProposedDeltaPayload>(fixture.input.clone())
            }
            "TurnProposedCompletedPayload" => {
                checked_roundtrip::<TurnProposedCompletedPayload>(fixture.input.clone())
            }
            "TurnDiffUpdatedPayload" => {
                checked_roundtrip::<TurnDiffUpdatedPayload>(fixture.input.clone())
            }
            "ContentDeltaPayload" => {
                checked_roundtrip::<ContentDeltaPayload>(fixture.input.clone())
            }
            "RequestOpenedPayload" => {
                checked_roundtrip::<RequestOpenedPayload>(fixture.input.clone())
            }
            "RequestResolvedPayload" => {
                checked_roundtrip::<RequestResolvedPayload>(fixture.input.clone())
            }
            "UserInputResolvedPayload" => {
                checked_roundtrip::<UserInputResolvedPayload>(fixture.input.clone())
            }
            "TaskStartedPayload" => checked_roundtrip::<TaskStartedPayload>(fixture.input.clone()),
            "TaskProgressPayload" => {
                checked_roundtrip::<TaskProgressPayload>(fixture.input.clone())
            }
            "TaskUpdatedPayload" => checked_roundtrip::<TaskUpdatedPayload>(fixture.input.clone()),
            "TaskCompletedPayload" => {
                checked_roundtrip::<TaskCompletedPayload>(fixture.input.clone())
            }
            "HookStartedPayload" => checked_roundtrip::<HookStartedPayload>(fixture.input.clone()),
            "HookProgressPayload" => {
                checked_roundtrip::<HookProgressPayload>(fixture.input.clone())
            }
            "HookCompletedPayload" => {
                checked_roundtrip::<HookCompletedPayload>(fixture.input.clone())
            }
            "ToolProgressPayload" => {
                checked_roundtrip::<ToolProgressPayload>(fixture.input.clone())
            }
            "ToolSummaryPayload" => checked_roundtrip::<ToolSummaryPayload>(fixture.input.clone()),
            "AuthStatusPayload" => checked_roundtrip::<AuthStatusPayload>(fixture.input.clone()),
            "AccountUpdatedPayload" => {
                checked_roundtrip::<AccountUpdatedPayload>(fixture.input.clone())
            }
            "AccountRateLimitsUpdatedPayload" => {
                checked_roundtrip::<AccountRateLimitsUpdatedPayload>(fixture.input.clone())
            }
            "McpStatusUpdatedPayload" => {
                checked_roundtrip::<McpStatusUpdatedPayload>(fixture.input.clone())
            }
            "McpOauthCompletedPayload" => {
                checked_roundtrip::<McpOauthCompletedPayload>(fixture.input.clone())
            }
            "ModelReroutedPayload" => {
                checked_roundtrip::<ModelReroutedPayload>(fixture.input.clone())
            }
            "ConfigWarningPayload" => {
                checked_roundtrip::<ConfigWarningPayload>(fixture.input.clone())
            }
            "DeprecationNoticePayload" => {
                checked_roundtrip::<DeprecationNoticePayload>(fixture.input.clone())
            }
            "FilesPersistedPayload" => {
                checked_roundtrip::<FilesPersistedPayload>(fixture.input.clone())
            }
            "ToolDeniedPayload" => checked_roundtrip::<ToolDeniedPayload>(fixture.input.clone()),
            "RuntimeWarningPayload" => {
                checked_roundtrip::<RuntimeWarningPayload>(fixture.input.clone())
            }
            "RuntimeErrorPayload" => {
                checked_roundtrip::<RuntimeErrorPayload>(fixture.input.clone())
            }
            "ProviderRuntimeEventBase" => {
                checked_roundtrip::<ProviderRuntimeEventBase>(fixture.input.clone())
            }
            "ProviderRefs" => checked_roundtrip::<ProviderRefs>(fixture.input.clone()),
            "RuntimeEventRawSource" => {
                checked_roundtrip::<RuntimeEventRawSource>(fixture.input.clone())
            }
            "RuntimeSessionState" => {
                checked_roundtrip::<RuntimeSessionState>(fixture.input.clone())
            }
            "RuntimeThreadState" => checked_roundtrip::<RuntimeThreadState>(fixture.input.clone()),
            "RuntimeTurnState" => checked_roundtrip::<RuntimeTurnState>(fixture.input.clone()),
            "RuntimePlanStep" => checked_roundtrip::<RuntimePlanStep>(fixture.input.clone()),
            "RuntimePlanStepStatus" => {
                checked_roundtrip::<RuntimePlanStepStatus>(fixture.input.clone())
            }
            "RuntimeItemStatus" => checked_roundtrip::<RuntimeItemStatus>(fixture.input.clone()),
            "RuntimeContentStreamKind" => {
                checked_roundtrip::<RuntimeContentStreamKind>(fixture.input.clone())
            }
            "RuntimeSessionExitKind" => {
                checked_roundtrip::<RuntimeSessionExitKind>(fixture.input.clone())
            }
            "RuntimeErrorClass" => checked_roundtrip::<RuntimeErrorClass>(fixture.input.clone()),
            "RuntimeUserInputQuestionOption" => {
                checked_roundtrip::<RuntimeUserInputQuestionOption>(fixture.input.clone())
            }
            "ProviderRef" => checked_roundtrip::<ProviderRef>(fixture.input.clone()),
            "ProviderThreadNativeMetadata" => {
                checked_roundtrip::<ProviderThreadNativeMetadata>(fixture.input.clone())
            }
            "LimitRecovery" => checked_roundtrip::<LimitRecovery>(fixture.input.clone()),
            "LimitRecoveryUpdate" => {
                checked_roundtrip::<LimitRecoveryUpdate>(fixture.input.clone())
            }
            "PendingBackgroundTask" => {
                checked_roundtrip::<PendingBackgroundTask>(fixture.input.clone())
            }
            "ThreadForkSourcePoint" => {
                checked_roundtrip::<ThreadForkSourcePoint>(fixture.input.clone())
            }
            "ConversationMessage" => {
                checked_roundtrip::<ConversationMessage>(fixture.input.clone())
            }
            "RuntimeRequest" => checked_roundtrip::<RuntimeRequest>(fixture.input.clone()),
            "ThreadProjection" => checked_roundtrip::<ThreadProjection>(fixture.input.clone()),
            "DomainEvent" => checked_roundtrip::<DomainEvent>(fixture.input.clone()),
            "ThreadStreamItem" => checked_roundtrip::<ThreadStreamItem>(fixture.input.clone()),
            "ThreadDetailSnapshot" => {
                checked_roundtrip::<ThreadDetailSnapshot>(fixture.input.clone())
            }
            "ThreadBoundedSnapshot" => {
                checked_roundtrip::<ThreadBoundedSnapshot>(fixture.input.clone())
            }
            "ThreadHistoryPage" => checked_roundtrip::<ThreadHistoryPage>(fixture.input.clone()),
            "GetTurnItemInput" => checked_roundtrip::<GetTurnItemInput>(fixture.input.clone()),
            "GetTurnItemResult" => checked_roundtrip::<GetTurnItemResult>(fixture.input.clone()),
            "GetThreadProjectionInput" => {
                checked_roundtrip::<GetThreadProjectionInput>(fixture.input.clone())
            }
            "SubscribeThreadInput" => {
                checked_roundtrip::<SubscribeThreadInput>(fixture.input.clone())
            }
            "SubscribeShellInput" => {
                checked_roundtrip::<SubscribeShellInput>(fixture.input.clone())
            }
            "SessionCapabilities" => {
                checked_roundtrip::<SessionCapabilities>(fixture.input.clone())
            }
            "ThreadCapabilities" => checked_roundtrip::<ThreadCapabilities>(fixture.input.clone()),
            "TurnCapabilities" => checked_roundtrip::<TurnCapabilities>(fixture.input.clone()),
            "StreamingCapabilities" => {
                checked_roundtrip::<StreamingCapabilities>(fixture.input.clone())
            }
            "ToolCapabilities" => checked_roundtrip::<ToolCapabilities>(fixture.input.clone()),
            "ApprovalCapabilities" => {
                checked_roundtrip::<ApprovalCapabilities>(fixture.input.clone())
            }
            "PlanningCapabilities" => {
                checked_roundtrip::<PlanningCapabilities>(fixture.input.clone())
            }
            "SubagentCapabilities" => {
                checked_roundtrip::<SubagentCapabilities>(fixture.input.clone())
            }
            "ContextCapabilities" => {
                checked_roundtrip::<ContextCapabilities>(fixture.input.clone())
            }
            "CheckpointCapabilities" => {
                checked_roundtrip::<CheckpointCapabilities>(fixture.input.clone())
            }
            "IdentityCapabilities" => {
                checked_roundtrip::<IdentityCapabilities>(fixture.input.clone())
            }
            "RuntimePolicyCapabilities" => {
                checked_roundtrip::<RuntimePolicyCapabilities>(fixture.input.clone())
            }
            "ProviderCapabilities" => {
                checked_roundtrip::<ProviderCapabilities>(fixture.input.clone())
            }
            "RunStatus" => checked_roundtrip::<RunStatus>(fixture.input.clone()),
            "DelegatedCompletionTaskDeliveryState" => {
                checked_roundtrip::<DelegatedCompletionTaskDeliveryState>(fixture.input.clone())
            }
            "DelegatedCompletionTaskDelivery" => {
                checked_roundtrip::<DelegatedCompletionTaskDelivery>(fixture.input.clone())
            }
            "DelegatedCompletionDelivery" => {
                checked_roundtrip::<DelegatedCompletionDelivery>(fixture.input.clone())
            }
            "DelegatedCompletionCohort" => {
                checked_roundtrip::<DelegatedCompletionCohort>(fixture.input.clone())
            }
            "RestartCancelledBackgroundWork" => {
                checked_roundtrip::<RestartCancelledBackgroundWork>(fixture.input.clone())
            }
            "RunBackgroundWorkCancelled" => {
                checked_roundtrip::<RunBackgroundWorkCancelled>(fixture.input.clone())
            }
            "ThreadLaunchWorkspaceStrategy" => {
                checked_roundtrip::<ThreadLaunchWorkspaceStrategy>(fixture.input.clone())
            }
            "Run" => checked_roundtrip::<Run>(fixture.input.clone()),
            "RunAttempt" => checked_roundtrip::<RunAttempt>(fixture.input.clone()),
            "ExecutionNode" => checked_roundtrip::<ExecutionNode>(fixture.input.clone()),
            "Subagent" => checked_roundtrip::<Subagent>(fixture.input.clone()),
            "CheckpointScope" => checked_roundtrip::<CheckpointScope>(fixture.input.clone()),
            "ProviderSessionDetached" => {
                checked_roundtrip::<ProviderSessionDetached>(fixture.input.clone())
            }
            "ProviderThread" => checked_roundtrip::<ProviderThread>(fixture.input.clone()),
            "ProviderTurnTokenUsage" => {
                checked_roundtrip::<ProviderTurnTokenUsage>(fixture.input.clone())
            }
            "ProviderTurn" => checked_roundtrip::<ProviderTurn>(fixture.input.clone()),
            "ProviderFailure" => checked_roundtrip::<ProviderFailure>(fixture.input.clone()),
            "ProviderRetry" => checked_roundtrip::<ProviderRetry>(fixture.input.clone()),
            "ThreadLaunchInput" => checked_roundtrip::<ThreadLaunchInput>(fixture.input.clone()),
            "ThreadLaunchResult" => checked_roundtrip::<ThreadLaunchResult>(fixture.input.clone()),
            "NotificationSource" => checked_roundtrip::<NotificationSource>(fixture.input.clone()),
            "Notification" => checked_roundtrip::<Notification>(fixture.input.clone()),
            "PlanStep" => checked_roundtrip::<PlanStep>(fixture.input.clone()),
            "PlanArtifact" => checked_roundtrip::<PlanArtifact>(fixture.input.clone()),
            "CheckpointFileSummary" => {
                checked_roundtrip::<CheckpointFileSummary>(fixture.input.clone())
            }
            "Checkpoint" => checked_roundtrip::<Checkpoint>(fixture.input.clone()),
            "CheckpointRollbackRequest" => {
                checked_roundtrip::<CheckpointRollbackRequest>(fixture.input.clone())
            }
            "TurnItemStatus" => checked_roundtrip::<TurnItemStatus>(fixture.input.clone()),
            "UserMessageInputIntent" => {
                checked_roundtrip::<UserMessageInputIntent>(fixture.input.clone())
            }
            "FileChangeDetail" => checked_roundtrip::<FileChangeDetail>(fixture.input.clone()),
            "FileSearchResult" => checked_roundtrip::<FileSearchResult>(fixture.input.clone()),
            "WebSearchResult" => checked_roundtrip::<WebSearchResult>(fixture.input.clone()),
            "SecretRequestStatus" => {
                checked_roundtrip::<SecretRequestStatus>(fixture.input.clone())
            }
            "TurnItem" => checked_roundtrip::<TurnItem>(fixture.input.clone()),
            "ProjectedTurnItem" => checked_roundtrip::<ProjectedTurnItem>(fixture.input.clone()),
            "HistoricalMessage" => checked_roundtrip::<HistoricalMessage>(fixture.input.clone()),
            "ContextHandoff" => checked_roundtrip::<ContextHandoff>(fixture.input.clone()),
            "ContextTransferType" => {
                checked_roundtrip::<ContextTransferType>(fixture.input.clone())
            }
            "ContextSourcePoint" => checked_roundtrip::<ContextSourcePoint>(fixture.input.clone()),
            "ContextTransferResolution" => {
                checked_roundtrip::<ContextTransferResolution>(fixture.input.clone())
            }
            "ContextTransfer" => checked_roundtrip::<ContextTransfer>(fixture.input.clone()),
            "ProviderSessionV2" => checked_roundtrip::<ProviderSessionV2>(fixture.input.clone()),
            "UserInputQuestionV2" => {
                checked_roundtrip::<UserInputQuestionV2>(fixture.input.clone())
            }
            "EnvironmentOrchestrationThreadSnapshotParams" => checked_roundtrip::<
                EnvironmentOrchestrationThreadSnapshotParams,
            >(fixture.input.clone()),
            "EnvironmentOrchestrationThreadHistoryQuery" => checked_roundtrip::<
                EnvironmentOrchestrationThreadHistoryQuery,
            >(fixture.input.clone()),
            "ThreadCommand" => checked_roundtrip::<ThreadCommand>(fixture.input.clone()),
            "ProviderCommand" => checked_roundtrip::<ProviderCommand>(fixture.input.clone()),
            // END ORIGINAL CODEC DISPATCH
            schema => panic!("unsupported fixture codec {schema}"),
        };
        if decoded_valid != fixture.decoded_valid.unwrap_or(fixture.valid)
            || result.is_ok() != fixture.valid
            || fixture.valid && result.as_ref().ok() != fixture.output.as_ref()
        {
            let count = counts.entry(fixture.schema.clone()).or_default();
            *count += 1;
            if *count <= 3 {
                failures.push(format!(
                    "{} input {}: Rust {:?}; original {:?}",
                    fixture.schema, fixture.input, result, fixture.output
                ));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} mismatches:\n{}",
        format!("{:?}", counts),
        failures.join("\n")
    );
}
